[package]
name = "pgorm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "A lightweight Postgres-only ORM for Rust"

[dependencies]
tokio-postgres.workspace = true
deadpool-postgres = { workspace = true, optional = true }
thiserror.workspace = true
chrono.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
pgorm-derive = { workspace = true, optional = true }

[dev-dependencies]
tokio.workspace = true

[features]
default = ["pool", "derive", "builder"]

pool = ["deadpool-postgres"]
derive = ["pgorm-derive"]

# Structured SQL builders (SELECT/INSERT/UPDATE/DELETE)
builder = []
