[package]
name = "pgorm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "A lightweight Postgres-only ORM for Rust"

[dependencies]
tokio-postgres.workspace = true
tokio = { workspace = true, features = ["time"] }
deadpool-postgres = { workspace = true, optional = true }
thiserror.workspace = true
chrono.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
pgorm-derive = { workspace = true, optional = true }
pgorm-check = { path = "../pgorm-check", features = ["sql"], optional = true }
inventory = "0.3"

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
dotenvy = "0.15"
colored.workspace = true
comfy-table.workspace = true

[features]
default = ["pool", "derive", "check"]

pool = ["deadpool-postgres"]
derive = ["pgorm-derive"]

# SQL schema checking and linting (via pgorm-check)
check = ["pgorm-check"]
